### ISSUE TITLE
the pre-trined model link in broken

### ISSUE THREAD

**Issue by ahronshor** [zekeriyyaa/MaskRCNN-Modanet-Fashion-Segmentation-and-Classification#1]
the link in readme to drive mask_rcnn_Modanet.h5 is broken.
Please give us a new link if you can.

**Comment by zekeriyyaa** [comment]
Thanks for your alert. You can access all project codes and document given [link](https://drive.google.com/file/d/10GJlbQ1fRXXF6fCu3SWkLeQBRKhaBYNf/view?usp=sharing) 
**mask_rcnn_Modanet.h5**  model is located at /model1/mask_rcnn_Modanet.h5  
And also you can access **mask_rcnn_Season.h5** model as well as /model2/mask_rcnn_Season.h5

**Comment by oo92** [comment]
Hocam. Link bozuk. .h5 dosyasi mevcut degil!
