### ISSUE TITLE
Model Download link Broken

### ISSUE THREAD

**Issue by littleGiant-28** [zekeriyyaa/MaskRCNN-Modanet-Fashion-Segmentation-and-Classification#4]
The following link provided in the Readme is broken: https://drive.google.com/file/d/1XEg4wqdz1G4yTcjeakBUh22YDw8Jf3f4/view?usp=sharing
Another link provided in #1,  https://drive.google.com/file/d/10GJlbQ1fRXXF6fCu3SWkLeQBRKhaBYNf/view?usp=sharing is also broken.

Can you please provide the new link?
Thanks.

**Comment by zekeriyyaa** [comment]
I'm afraid these links are deleted accidentally.
